"""initial schema

Revision ID: 85924c308070
Revises: 
Create Date: 2026-04-18 22:31:09.073510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85924c308070'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('category', sa.Enum('rekindle', 'upgrade', 'maintain', name='category'), nullable=False),
    sa.Column('cadence', sa.Enum('weekly', 'biweekly', 'monthly', 'quarterly', name='cadence'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_cadence'), 'friend', ['cadence'], unique=False)
    op.create_index(op.f('ix_friend_category'), 'friend', ['category'], unique=False)
    op.create_index(op.f('ix_friend_name'), 'friend', ['name'], unique=False)
    op.create_table('sync_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('ifttt', 'google_calendar', name='syncprovider'), nullable=False),
    sa.Column('entity_type', sa.Enum('friend', 'interaction', 'calendar_link', name='syncentitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'append', name='syncaction'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='syncstatus'), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_event_entity_id'), 'sync_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_event_entity_type'), 'sync_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_event_provider'), 'sync_event', ['provider'], unique=False)
    op.create_index(op.f('ix_sync_event_status'), 'sync_event', ['status'], unique=False)
    op.create_table('calendar_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('google_calendar', name='calendarprovider'), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friend_id', 'provider', name='uq_calendar_link_friend_provider')
    )
    op.create_index(op.f('ix_calendar_link_external_event_id'), 'calendar_link', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_link_friend_id'), 'calendar_link', ['friend_id'], unique=False)
    op.create_table('friend_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friend_id', 'tag', name='uq_friend_tag_friend_tag')
    )
    op.create_index(op.f('ix_friend_tag_friend_id'), 'friend_tag', ['friend_id'], unique=False)
    op.create_index(op.f('ix_friend_tag_tag'), 'friend_tag', ['tag'], unique=False)
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('interaction_type', sa.Enum('message', 'call', 'in_person', 'email', 'other', name='interactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_friend_id'), 'interaction', ['friend_id'], unique=False)
    op.create_index('ix_interaction_friend_occurred', 'interaction', ['friend_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interaction_occurred_at'), 'interaction', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_occurred_at'), table_name='interaction')
    op.drop_index('ix_interaction_friend_occurred', table_name='interaction')
    op.drop_index(op.f('ix_interaction_friend_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_friend_tag_tag'), table_name='friend_tag')
    op.drop_index(op.f('ix_friend_tag_friend_id'), table_name='friend_tag')
    op.drop_table('friend_tag')
    op.drop_index(op.f('ix_calendar_link_friend_id'), table_name='calendar_link')
    op.drop_index(op.f('ix_calendar_link_external_event_id'), table_name='calendar_link')
    op.drop_table('calendar_link')
    op.drop_index(op.f('ix_sync_event_status'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_provider'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_entity_type'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_entity_id'), table_name='sync_event')
    op.drop_table('sync_event')
    op.drop_index(op.f('ix_friend_name'), table_name='friend')
    op.drop_index(op.f('ix_friend_category'), table_name='friend')
    op.drop_index(op.f('ix_friend_cadence'), table_name='friend')
    op.drop_table('friend')
    # ### end Alembic commands ###
